export const SITE_URL = process.env.SITE_URL || ''

export const FEATURE_FILTERS: { id: string; name: string; emoji: string }[] = [
  { id: 'coa', name: 'COA', emoji: '📋' },
  { id: 'credit-card', name: 'Credit Card', emoji: '💳' },
  { id: 'ach', name: 'ACH', emoji: '🏦' },
  { id: 'crypto', name: 'Crypto', emoji: '' },
  { id: 'fast-shipping', name: 'Fast Shipping', emoji: '⚡' },
  { id: 'international', name: 'International', emoji: '🌍' },
]

export const COMPOUNDS: { id: string; name: string }[] = [
  { id: '5-amino-1mq', name: '5-Amino-1MQ' },
  { id: 'acetic-acid', name: 'Acetic Acid' },
  { id: 'adamax', name: 'Adamax' },
  { id: 'adipotide', name: 'Adipotide' },
  { id: 'ahk-cu', name: 'AHK-CU' },
  { id: 'aicar', name: 'AICAR' },
  { id: 'aod-9604', name: 'AOD-9604' },
  { id: 'ara-290', name: 'ARA-290' },
  { id: 'astaxanthin', name: 'Astaxanthin' },
  { id: 'b-12', name: 'B-12' },
  { id: 'bacteriostatic-water', name: 'Bacteriostatic Water' },
  { id: 'bpc-157', name: 'BPC-157' },
  { id: 'bpc-157-ghk-cu', name: 'BPC-157/GHK-CU' },
  { id: 'bpc-157-tb-500', name: 'BPC-157/TB-500' },
  { id: 'bronchogen', name: 'Bronchogen' },
  { id: 'cagrilintide', name: 'Cagrilintide' },
  { id: 'cagrilintide-ipamorelin', name: 'Cagrilintide/Ipamorelin' },
  { id: 'cagrilintide-semaglutide', name: 'Cagrilintide/Semaglutide' },
  { id: 'cardiogen', name: 'Cardiogen' },
  { id: 'cartalax', name: 'Cartalax' },
  { id: 'cjc-1295', name: 'CJC-1295' },
  { id: 'cjc-1295-ipamorelin', name: 'CJC-1295/Ipamorelin' },
  { id: 'cortagen', name: 'Cortagen' },
  { id: 'dsip', name: 'DSIP' },
  { id: 'epitalon', name: 'Epitalon' },
  { id: 'follistatin-344', name: 'Follistatin-344' },
  { id: 'foxo4-dri', name: 'FOXO4-DRI' },
  { id: 'ghk-cu', name: 'GHK-CU' },
  { id: 'ghrp-2', name: 'GHRP-2' },
  { id: 'ghrp-6', name: 'GHRP-6' },
  { id: 'glow', name: 'GLOW' },
  { id: 'glutathione', name: 'Glutathione' },
  { id: 'gonadorelin', name: 'Gonadorelin' },
  { id: 'hcg', name: 'HCG' },
  { id: 'hexarelin', name: 'Hexarelin' },
  { id: 'hgh-frag-176-191', name: 'HGH Frag 176-191' },
  { id: 'hmg', name: 'HMG' },
  { id: 'humanin', name: 'Humanin' },
  { id: 'igf-1-lr3', name: 'IGF-1 LR3' },
  { id: 'ipamorelin', name: 'Ipamorelin' },
  { id: 'kisspeptin', name: 'Kisspeptin' },
  { id: 'klow', name: 'KLOW' },
  { id: 'kpv', name: 'KPV' },
  { id: 'l-carnitine', name: 'L-Carnitine' },
  { id: 'lipo-c', name: 'Lipo-C' },
  { id: 'lipo-c-b-12', name: 'Lipo-C/B-12' },
  { id: 'll-37', name: 'LL-37' },
  { id: 'mazdutide', name: 'Mazdutide' },
  { id: 'melanotan-i', name: 'Melanotan I' },
  { id: 'melanotan-ii', name: 'Melanotan II' },
  { id: 'mots-c', name: 'MOTS-C' },
  { id: 'nad-plus', name: 'NAD+' },
  { id: 'nad-plus-buffered', name: 'NAD+ Buffered' },
  { id: 'oxytocin', name: 'Oxytocin' },
  { id: 'p-21', name: 'P-21' },
  { id: 'pancragen', name: 'Pancragen' },
  { id: 'pda', name: 'PDA' },
  { id: 'pe-12-28', name: 'PE 12-28' },
  { id: 'pe-22-28', name: 'PE-22-28' },
  { id: 'peg-mgf', name: 'PEG-MGF' },
  { id: 'pinealon', name: 'Pinealon' },
  { id: 'pnc-27', name: 'PNC-27' },
  { id: 'pnc-28', name: 'PNC-28' },
  { id: 'pt-141', name: 'PT-141' },
  { id: 'retatrutide', name: 'Retatrutide' },
  { id: 'retatrutide-cagrilintide', name: 'Retatrutide/Cagrilintide' },
  { id: 'retatrutide-tirzepatide', name: 'Retatrutide/Tirzepatide' },
  { id: 'selank', name: 'Selank' },
  { id: 'semaglutide', name: 'Semaglutide' },
  { id: 'semax', name: 'Semax' },
  { id: 'semax-selank', name: 'Semax/Selank' },
  { id: 'sermorelin', name: 'Sermorelin' },
  { id: 'slu-pp-332', name: 'SLU-PP-332' },
  { id: 'snap-8', name: 'Snap-8' },
  { id: 'ss-31', name: 'SS-31' },
  { id: 'survodutide', name: 'Survodutide' },
  { id: 'tb-500', name: 'TB-500' },
  { id: 'tb-500-frag-17-23', name: 'TB-500/Frag 17-23' },
  { id: 'tesamorelin', name: 'Tesamorelin' },
  { id: 'tesamorelin-ipamorelin', name: 'Tesamorelin/Ipamorelin' },
  { id: 'testagen', name: 'Testagen' },
  { id: 'thymagen', name: 'Thymagen' },
  { id: 'thymalin', name: 'Thymalin' },
  { id: 'thymosin-alpha-1', name: 'Thymosin Alpha 1' },
  { id: 'thymulin', name: 'Thymulin' },
  { id: 'tirzepatide', name: 'Tirzepatide' },
  { id: 'vesugen', name: 'Vesugen' },
  { id: 'vilon', name: 'Vilon' },
  { id: 'vip', name: 'VIP' },
]

export const COUNTRIES = [
  'All Countries',
  'USA',
] as const
