export const PEPTIDE_ICON_LABELS: Record<string, string> = {
  '5-amino-1mq': '5-AMINO',
  'acetic-acid': 'ACETIC\nACID',
  adamax: 'ADAMAX',
  adipotide: 'ADI',
  'ahk-cu': 'AHK-CU',
  aicar: 'AICAR',
  'aod-9604': 'AOD-9604',
  'ara-290': 'ARA-290',
  astaxanthin: 'ASTAX',
  'b-12': 'B-12',
  'bacteriostatic-water': 'BAC\nWATER',
  'bpc-157': 'BPC-157',
  'bpc-157-ghk-cu': 'BPC/GHK',
  'bpc-157-tb-500': 'BPC/TB',
  bronchogen: 'BR',
  cagrilintide: 'CARGI',
  'cagrilintide-ipamorelin': 'CARGI/IPA',
  'cagrilintide-semaglutide': 'CARGI/SEMA',
  cardiogen: 'CARD',
  cartalax: 'CARTA',
  'cjc-1295': 'CJC-1295',
  'cjc-1295-ipamorelin': 'CJC/IPA',
  cortagen: 'CORTA',
  dsip: 'DSIP',
  epitalon: 'EPI',
  'follistatin-344': 'FOLI',
  'foxo4-dri': 'FOX-DRI',
  'ghk-cu': 'GHK-CU',
  'ghrp-2': 'GHRP-2',
  'ghrp-6': 'GHRP-6',
  glow: 'GLOW',
  glutathione: 'GLUTA',
  gonadorelin: 'GONA',
  hcg: 'HCG',
  hexarelin: 'HEXA',
  'hgh-frag-176-191': 'HGH\nFRAG',
  hmg: 'HMG',
  humanin: 'HUMA',
  'igf-1-lr3': 'IGF',
  ipamorelin: 'IPA',
  kisspeptin: 'KISS',
  klow: 'KLOW',
  kpv: 'KPV',
  'l-carnitine': 'L-CARN',
  'lipo-c': 'LIPO-C',
  'lipo-c-b-12': 'LIPO/B-12',
  'll-37': 'LL-37',
  mazdutide: 'MAZA',
  'melanotan-i': 'MT-1',
  'melanotan-ii': 'MT-2',
  'mots-c': 'MOTS-C',
  'nad-plus': 'NAD+',
  'nad-plus-buffered': 'NAD+\nBUFFERED',
  oxytocin: 'OXY',
  'p-21': 'P-21',
  pancragen: 'PANC',
  pda: 'PDA',
  'pe-12-28': 'PE-12',
  'pe-22-28': 'PE-22',
  'peg-mgf': 'PEG',
  pinealon: 'PINE',
  'pnc-27': 'PNC-27',
  'pnc-28': 'PNC-28',
  'pt-141': 'PT-141',
  retatrutide: 'RETA',
  'retatrutide-cagrilintide': 'RETA/CAGR',
  'retatrutide-tirzepatide': 'RETA/TIRZ',
  selank: 'SELANK',
  semaglutide: 'SEMA',
  semax: 'SEMAX',
  'semax-selank': 'SEMAX\nSELANK',
  sermorelin: 'SERM',
  'slu-pp-332': 'SLU-PP',
  'snap-8': 'SNAP',
  'ss-31': 'SS',
  survodutide: 'SURV',
  'tb-500': 'TB-500',
  'tb-500-frag-17-23': 'TB/FRAG',
  tesamorelin: 'TESA',
  'tesamorelin-ipamorelin': 'TESA/IPA',
  testagen: 'TEST',
  thymagen: 'THYM\nAGEN',
  thymalin: 'THYMALIN',
  'thymosin-alpha-1': 'TA-1',
  thymulin: 'THYMULIN',
  tirzepatide: 'TIRZ',
  vesugen: 'VESU',
  vilon: 'VILON',
  vip: 'VIP',
}

function peptideInitials(name: string) {
  return name.replace(/[^a-zA-Z0-9]/g, '').slice(0, 2).toUpperCase() || 'PE'
}

export function peptideIconLabel(id: string, name: string) {
  return PEPTIDE_ICON_LABELS[id] ?? peptideInitials(name)
}

export function peptideGradient() {
  return 'linear-gradient(135deg, #d1fae5, #eff6ff, #ffe4e6)'
}
