/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompoundRouteImport } from './routes/$compound'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIdRouteImport } from './routes/vendors.$id'

const CompoundRoute = CompoundRouteImport.update({
  id: '/$compound',
  path: '/$compound',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$compound': typeof CompoundRoute
  '/vendors/$id': typeof VendorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$compound': typeof CompoundRoute
  '/vendors/$id': typeof VendorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$compound': typeof CompoundRoute
  '/vendors/$id': typeof VendorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$compound' | '/vendors/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$compound' | '/vendors/$id'
  id: '__root__' | '/' | '/$compound' | '/vendors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompoundRoute: typeof CompoundRoute
  VendorsIdRoute: typeof VendorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$compound': {
      id: '/$compound'
      path: '/$compound'
      fullPath: '/$compound'
      preLoaderRoute: typeof CompoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompoundRoute: CompoundRoute,
  VendorsIdRoute: VendorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
