/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PeptidesRouteImport } from './routes/peptides'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as PeptidesIndexRouteImport } from './routes/peptides.index'
import { Route as VendorsIdRouteImport } from './routes/vendors.$id'
import { Route as PeptidesCompoundRouteImport } from './routes/peptides.$compound'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PeptidesRoute = PeptidesRouteImport.update({
  id: '/peptides',
  path: '/peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorsRoute,
} as any)
const PeptidesIndexRoute = PeptidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeptidesRoute,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VendorsRoute,
} as any)
const PeptidesCompoundRoute = PeptidesCompoundRouteImport.update({
  id: '/$compound',
  path: '/$compound',
  getParentRoute: () => PeptidesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calculator': typeof CalculatorRoute
  '/favorites': typeof FavoritesRoute
  '/peptides': typeof PeptidesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/peptides/$compound': typeof PeptidesCompoundRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/peptides/': typeof PeptidesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calculator': typeof CalculatorRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/peptides/$compound': typeof PeptidesCompoundRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/peptides': typeof PeptidesIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calculator': typeof CalculatorRoute
  '/favorites': typeof FavoritesRoute
  '/peptides': typeof PeptidesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/peptides/$compound': typeof PeptidesCompoundRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/peptides/': typeof PeptidesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/calculator'
    | '/favorites'
    | '/peptides'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/vendors'
    | '/peptides/$compound'
    | '/vendors/$id'
    | '/peptides/'
    | '/vendors/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/calculator'
    | '/favorites'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/peptides/$compound'
    | '/vendors/$id'
    | '/peptides'
    | '/vendors'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/calculator'
    | '/favorites'
    | '/peptides'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/vendors'
    | '/peptides/$compound'
    | '/vendors/$id'
    | '/peptides/'
    | '/vendors/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CalculatorRoute: typeof CalculatorRoute
  FavoritesRoute: typeof FavoritesRoute
  PeptidesRoute: typeof PeptidesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VendorsRoute: typeof VendorsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peptides': {
      id: '/peptides'
      path: '/peptides'
      fullPath: '/peptides'
      preLoaderRoute: typeof PeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/peptides/': {
      id: '/peptides/'
      path: '/'
      fullPath: '/peptides/'
      preLoaderRoute: typeof PeptidesIndexRouteImport
      parentRoute: typeof PeptidesRoute
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/peptides/$compound': {
      id: '/peptides/$compound'
      path: '/$compound'
      fullPath: '/peptides/$compound'
      preLoaderRoute: typeof PeptidesCompoundRouteImport
      parentRoute: typeof PeptidesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PeptidesRouteChildren {
  PeptidesCompoundRoute: typeof PeptidesCompoundRoute
  PeptidesIndexRoute: typeof PeptidesIndexRoute
}

const PeptidesRouteChildren: PeptidesRouteChildren = {
  PeptidesCompoundRoute: PeptidesCompoundRoute,
  PeptidesIndexRoute: PeptidesIndexRoute,
}

const PeptidesRouteWithChildren = PeptidesRoute._addFileChildren(
  PeptidesRouteChildren,
)

interface VendorsRouteChildren {
  VendorsIdRoute: typeof VendorsIdRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

const VendorsRouteChildren: VendorsRouteChildren = {
  VendorsIdRoute: VendorsIdRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}

const VendorsRouteWithChildren =
  VendorsRoute._addFileChildren(VendorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CalculatorRoute: CalculatorRoute,
  FavoritesRoute: FavoritesRoute,
  PeptidesRoute: PeptidesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VendorsRoute: VendorsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
